### ISSUE TITLE
Support several buttons pressed

### ISSUE THREAD

**Issue by s-celles** [ArduinoGetStarted/Analog-Keypad#3]
Hello,

It's unclear to me if this library support multipressed buttons.

I don't think so.

If that's not the case maybe it could be done by passing to getKeys method a reference of an array of n buttons which could contains state of each button (ie pressed or released).

This method could return number of pressed buttons.

This kind of conversion is an analog to digital conversion.

Any opinion ?

Kind regards

**Comment by ArduinoGetStarted** [comment]
Dear @scls19fr 

I am sorry for the late reply.
Thank you for your comment. 
I think it is impossible to detect multiple press/release when using a single Analog pin. If you know any  method to realize it, please share it.  I am happy to learn more.

Best regards,

**Comment by s-celles** [comment]
Thanks @ArduinoGetStarted 
It seems that it is impossible to do that.
So I'm closing.
